UiShopItem: "347:0"
UiShopItemName: "§a道具商店"
UiShopItemLore: |-
  便携道具商店
  购买各种道具来帮助你获取胜利！
ShopMain: "§a你当前有 §e %gold% §a块金锭"
ShopPrice: "价格: %gold% 块金锭"
BuyOK: "§a确定要花费 §e %gold% §a块金锭购买 §e %item% §a？"
ButtonOK: "§a购买"
ButtonReturn: "§c返回"
BuySuccess: "§a成功兑换到: §e %item% §a已发放到背包！"
BuyFailure: "§a你的金锭数量不足！"
#格式  道具内部ID:显示名称:购买价格(金锭)
#format  Props internal ID:display name:purchase price (gold ingot)
#道具内部id请参考 https://github.com/lt-name/MurderMystery_Nukkit/wiki/Item-ID
items:
  - 21:神秘药水:1
  - 22:护盾生成器:2
  - 23:减速雪球:1